name: check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Check
        run: cargo check --all-targets

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Format
        run: cargo fmt --check
