name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Start SpiceDB
        uses: authzed/action-spicedb@v1
        with:
          version: latest

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      - name: Run tests
        env:
          SPICEDB_ENDPOINT: 127.0.0.1:50051
        run: cargo test --workspace --all-targets -- --nocapture
